@url = http://localhost:5000

###
# @name create_cinema
POST {{url}}/cinemas 
Content-Type: application/json

{
	"id" : "1c6b9a50-751d-4aa2-ae40-41778bcaf007",
	"name" : "Cinema",
	"address": {
		"city": "Warsaw",
		"street": "Test street 21",
		"zipCode": "05-000"
	},
	"halls" : [{
        "id" : "102876d1-8b38-4dbd-87ff-832746ab6656",
        "name": "A",
        "seats": [{
            "row" : "F",
            "number" : 12
        }]
	},
	{
        "id" : "202876d1-8b38-4dbd-87ff-832746ab6656",
        "name": "B",
        "seats": [{
            "row" : "F",
            "number" : 12
        }]
	},
	{
        "id" : "302876d1-8b38-4dbd-87ff-832746ab6656",        
        "name": "C",
        "seats": [{
            "row" : "F",
            "number" : 12
        }]
	},
	{
        "id" : "402876d1-8b38-4dbd-87ff-832746ab6656",
        "name": "D",
        "seats": [{
            "row" : "F",
            "number" : 12
        }]
	}]	
}

@cinemaId = {{create_cinema.response.headers.Location}}

###
GET {{url}}/cinemas/{{cinemaId}}



###
# @name create_movie
POST {{url}}/movies 
Content-Type: application/json

{
	"id" : "22a25313-da8c-4298-9cbd-49c99f1644ad",
	"title": "AwesomeMovie",
	"ageRestriction" : 10,
	"length": 123,
	"genre": "action",
    "premiereDate" : "2009-10-29"
}

@movieId = {{create_movie.response.headers.Location}}

###
GET {{url}}/movies/{{movieId}}

###
POST {{url}}/schedules/schema
Content-Type: application/json

{
    "id" : "9ca578df-4d08-4651-a555-f23fc2b5a79b",
    "cinemaId" : "1c6b9a50-751d-4aa2-ae40-41778bcaf007",
    "times": [
        {
            "ageRestriction": 3,
            "times" : [
                {
                    "hour" : 12,
                    "minute" : 0
                },
                {
                    "hour" : 16,
                    "minute" : 0
                }
            ]
        },
        {
            "ageRestriction": 16,
            "times" : [
                {
                    "hour" : 14,
                    "minute" : 30
                },
                {
                    "hour" : 16,
                    "minute" : 30
                },
                {
                    "hour" : 19,
                    "minute" : 45
                }
            ]
        },
        {
            "ageRestriction": 18,
            "times" : [
                {
                    "hour" : 20,
                    "minute" : 30
                },
                {
                    "hour" : 22,
                    "minute" : 30
                }
            ]
        }
    ]
}


###
POST {{url}}/schedules/generate
Content-Type: application/json

{
    "id" : "902876d1-8b38-4dbd-87ff-832746ab6656",  
    "cinemaId" :  "{{cinemaId}}",
    "movieId" : "{{movieId}}",
    "from" : "2020-01-10",
    "to" : "2020-01-20"
}

###
GET {{url}}/schedules/weekly?cinemaId={{cinemaId}}&movieId={{movieId}}


###
# @name create_reservation
POST {{url}}/reservations
Content-Type: application/json

{
    "id" : "132876d1-8b38-4dbd-87ff-832746ab6656",
    "cinemaId" : "{{cinemaId}}",
    "movieId" : "{{movieId}}",
    "hallId" : "102876d1-8b38-4dbd-87ff-832746ab6656",
    "seats" : [{
        "row" : "F",
        "number" : 12,
        "isVip" : true,
        "price" : 20.50
    }],
    "reservee" : {
        "fullName" : "John Smith",
        "email" : "test@mail.com",
        "phoneNumber" : "+48 602 781 895"
    }
}


@reservationId = {{create_reservation.response.headers.Location}}

###
GET {{url}}/reservations/132876d1-8b38-4dbd-87ff-832746ab6656